language: php
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0

before_install:
  - composer self-update
  #- composer require "codeception/codeception:${CODECEPTION_VERSION}"
install:
  - composer install --dev

script:
  - ./vendor/bin/codecept run acceptance
