language: php
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1 CODECEPTION_VERSION=2.1.11
#    - php: 5.5
#      env: WP_VERSION=latest WP_MULTISITE=0 CODECEPTION_VERSION=2.1.11
#    - php: 5.6
#      env: WP_VERSION=latest WP_MULTISITE=1 CODECEPTION_VERSION=2.2
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 CODECEPTION_VERSION=2.2
#    - php: 7.0
#      env: WP_VERSION=latest WP_MULTISITE=1 CODECEPTION_VERSION=2.2
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 CODECEPTION_VERSION=2.2

before_install:
  - composer self-update
  - composer require "codeception/codeception:${CODECEPTION_VERSION}"
install:
  - composer install --dev

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  -phantomjs phantomjs/test_runner.js

script:
  -phpunit
